name: Deploy Database Schema

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy DACPAC
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'


      - name: Build SQL Project
        run: |
          dotnet build \
            --configuration Release


      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: e5118c48-bd63-45bc-8c9c-c97fe9fa6c29
          tenant-id: 6c560666-4010-488d-90f9-57963cc5a7bf
          subscription-id: 48ab377d-9bc4-4f07-9ac8-fa30fbaab28b
          allow-no-subscriptions: true


      - name: Install SqlPackage
        run: |
          wget -q https://aka.ms/sqlpackage-linux -O sqlpackage.zip
          unzip -q sqlpackage.zip -d sqlpackage
          chmod +x sqlpackage/sqlpackage


      - name: Deploy DACPAC
        run: |
          ./sqlpackage/sqlpackage \
            /Action:Publish \
            /SourceFile:"bin/Release/stackoverflow2010-database.dacpac" \
            /TargetConnectionString:"Server=tcp:sqlserver-stack-test.database.windows.net,1433;Initial Catalog=StackOverflow2010;Authentication=Active Directory Default;"